# Generated by Django 4.2 on 2026-06-13 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Port",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("country", models.CharField(blank=True, max_length=60)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                (
                    "radius_nm",
                    models.FloatField(
                        default=15.0, help_text="Geofence radius in nautical miles"
                    ),
                ),
                (
                    "port_type",
                    models.CharField(
                        choices=[
                            ("load", "Load"),
                            ("discharge", "Discharge"),
                            ("both", "Both"),
                        ],
                        max_length=10,
                    ),
                ),
                ("basin", models.CharField(default="pacific", max_length=30)),
                (
                    "vessel_classes",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Classes this port serves, e.g. ['capesize','panamax']. Empty = all.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TrackedVessel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mmsi", models.BigIntegerField(db_index=True, unique=True)),
                ("imo", models.BigIntegerField(blank=True, null=True)),
                ("name", models.CharField(blank=True, max_length=120)),
                (
                    "ais_ship_type",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "length_m",
                    models.FloatField(
                        blank=True, help_text="AIS dimension A + B (metres)", null=True
                    ),
                ),
                (
                    "beam_m",
                    models.FloatField(
                        blank=True, help_text="AIS dimension C + D (metres)", null=True
                    ),
                ),
                (
                    "vessel_class",
                    models.CharField(
                        choices=[
                            ("capesize", "Capesize"),
                            ("panamax", "Panamax"),
                            ("supramax", "Supramax"),
                            ("handysize", "Handysize"),
                            ("unknown", "Unknown"),
                        ],
                        db_index=True,
                        default="unknown",
                        max_length=20,
                    ),
                ),
                (
                    "max_draught_m",
                    models.FloatField(
                        default=0.0, help_text="Maximum draught ever observed"
                    ),
                ),
                ("first_seen", models.DateTimeField(auto_now_add=True)),
                ("last_seen", models.DateTimeField(db_index=True)),
                (
                    "is_excluded",
                    models.BooleanField(
                        default=False,
                        help_text="Manually exclude from supply aggregates",
                    ),
                ),
            ],
            options={
                "ordering": ["name", "mmsi"],
            },
        ),
        migrations.CreateModel(
            name="VesselState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("speed_knots", models.FloatField(blank=True, null=True)),
                ("course", models.FloatField(blank=True, null=True)),
                ("draught_m", models.FloatField(blank=True, null=True)),
                ("nav_status", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "loading_condition",
                    models.CharField(
                        choices=[
                            ("laden", "Laden"),
                            ("ballast", "Ballast"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=10,
                    ),
                ),
                ("port_arrived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "position_at",
                    models.DateTimeField(
                        help_text="Timestamp of the last accepted position"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "current_port",
                    models.ForeignKey(
                        blank=True,
                        help_text="Port whose geofence the vessel is currently inside (null = at sea)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vessels_in_port",
                        to="supply.port",
                    ),
                ),
                (
                    "vessel",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="state",
                        to="supply.trackedvessel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SupplySignal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("vessel_class", models.CharField(max_length=20)),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("bullish", "Bullish"),
                            ("bearish", "Bearish"),
                            ("neutral", "Neutral"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "score",
                    models.FloatField(help_text="Signed magnitude, roughly -3..+3"),
                ),
                ("confidence", models.FloatField(help_text="0..1")),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("regression", "Regression"),
                            ("zscore", "Z-score heuristic"),
                            ("insufficient", "Insufficient data"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "drivers",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Plain-English driver strings",
                    ),
                ),
                ("data_days", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["-date", "vessel_class"],
                "unique_together": {("date", "vessel_class")},
            },
        ),
        migrations.CreateModel(
            name="PortCallEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[("arrival", "Arrival"), ("departure", "Departure")],
                        max_length=10,
                    ),
                ),
                ("timestamp", models.DateTimeField(db_index=True)),
                ("draught_m", models.FloatField(blank=True, null=True)),
                (
                    "loading_condition",
                    models.CharField(
                        choices=[
                            ("laden", "Laden"),
                            ("ballast", "Ballast"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=10,
                    ),
                ),
                (
                    "port",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calls",
                        to="supply.port",
                    ),
                ),
                (
                    "vessel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="port_calls",
                        to="supply.trackedvessel",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="DailySupplySnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("vessel_class", models.CharField(db_index=True, max_length=20)),
                ("basin", models.CharField(default="pacific", max_length=30)),
                ("in_port_load_count", models.PositiveIntegerField(default=0)),
                ("in_port_discharge_count", models.PositiveIntegerField(default=0)),
                ("ballast_at_sea_count", models.PositiveIntegerField(default=0)),
                ("laden_at_sea_count", models.PositiveIntegerField(default=0)),
                ("expected_open_7d", models.PositiveIntegerField(default=0)),
                ("expected_open_14d", models.PositiveIntegerField(default=0)),
                (
                    "total_tracked",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Fresh vessels (seen < staleness window) in basin",
                    ),
                ),
                ("arrivals_load_24h", models.PositiveIntegerField(default=0)),
                ("departures_load_24h", models.PositiveIntegerField(default=0)),
                ("arrivals_discharge_24h", models.PositiveIntegerField(default=0)),
                ("departures_discharge_24h", models.PositiveIntegerField(default=0)),
                ("avg_speed_laden", models.FloatField(blank=True, null=True)),
                ("avg_speed_ballast", models.FloatField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-date", "vessel_class"],
                "unique_together": {("date", "vessel_class", "basin")},
            },
        ),
        migrations.AddIndex(
            model_name="portcallevent",
            index=models.Index(
                fields=["port", "timestamp"], name="supply_port_port_id_f0fbfd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="portcallevent",
            index=models.Index(
                fields=["vessel", "timestamp"], name="supply_port_vessel__cb78f1_idx"
            ),
        ),
    ]
