# Generated by Django 4.2 on 2026-03-30

from django.db import migrations, models
import django.db.models.deletion


DEFAULT_INDEXES_BY_VESSEL = {
    'capesize': [
        'C2', 'C3', 'C5', 'C7', 'C8_14', 'C9_14', 'C10_14', 'C14', 'C16', 'C17',
        'BCI 5TC', 'BCI 4TC', 'BCI Index', 'Minicape (Old)', 'Minicape (Broker)',
        'Minicape (AVG)', 'Forward Capesize (Current)', 'Forward Capesize (Next MTH)',
        'Forward Panamax (Current)', 'Forward Panamax (Next Mth)',
        'Forward Minicape (Old) (Current)', 'Forward Minicape (Old) (Next Mth)',
        'Forward Minicape (Broker) (Current)', 'Forward Minicape (Broker) (Next Mth)',
    ],
    'panamax': ['P1A_82', 'P2A_82', 'P3A_82', 'P4A_82', 'P5_82', 'BPI 82TC', 'BPI Index'],
    'supramax': ['S1B_58', 'S1C_58', 'S2_58', 'S3_58', 'S4A_58', 'S4B_58', 'BSI 58TC', 'BSI Index'],
    'handysize': ['HS1', 'HS2', 'HS3', 'HS4', 'HS5', 'BHSI 38TC', 'BHSI Index'],
}


def seed_available_indices(apps, schema_editor):
    AvailableIndex = apps.get_model('voyage', 'AvailableIndex')

    for vessel_size, names in DEFAULT_INDEXES_BY_VESSEL.items():
        for idx, name in enumerate(names, start=1):
            AvailableIndex.objects.get_or_create(
                name=name,
                defaults={
                    'vessel_size': vessel_size,
                    'order': idx,
                    'is_active': True,
                },
            )


class Migration(migrations.Migration):

    dependencies = [
        ('voyage', '0002_customindexpreset'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('vessel_size', models.CharField(choices=[('capesize', 'Capesize'), ('panamax', 'Panamax'), ('supramax', 'Supramax'), ('handysize', 'Handysize')], max_length=20)),
                ('order', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Available Index',
                'verbose_name_plural': 'Available Indices',
                'ordering': ['vessel_size', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DailyIndexValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('value', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_values', to='voyage.availableindex')),
            ],
            options={
                'verbose_name': 'Daily Index Value',
                'verbose_name_plural': 'Daily Index Values',
                'ordering': ['-date', 'index__name'],
                'unique_together': {('index', 'date')},
            },
        ),
        migrations.RunPython(seed_available_indices, migrations.RunPython.noop),
    ]
