# Generated by Django 4.2 on 2026-04-02 06:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("voyage", "0004_seed_bunker_indices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="availableindex",
            name="vessel_size",
            field=models.CharField(
                choices=[
                    ("capesize", "Capesize"),
                    ("panamax", "Panamax"),
                    ("supramax", "Supramax"),
                    ("handysize", "Handysize"),
                    ("bunker", "Bunker"),
                ],
                max_length=20,
            ),
        ),
    ]
