# Generated by Django 4.2 on 2026-04-02 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("voyage", "0005_alter_availableindex_vessel_size"),
    ]

    operations = [
        migrations.CreateModel(
            name="VesselProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                (
                    "vessel_size",
                    models.CharField(
                        choices=[
                            ("capesize", "Capesize"),
                            ("panamax", "Panamax"),
                            ("supramax", "Supramax"),
                            ("handysize", "Handysize"),
                            ("bunker", "Bunker"),
                        ],
                        default="panamax",
                        max_length=20,
                    ),
                ),
                ("dwt", models.FloatField(help_text="Deadweight in metric tons")),
                ("draft", models.FloatField(help_text="Design draft in meters")),
                (
                    "npc",
                    models.FloatField(
                        default=0,
                        help_text="Non-performance claims or daily fixed cost, optional",
                    ),
                ),
                (
                    "grain_capacity",
                    models.FloatField(help_text="Grain capacity in cubic meters"),
                ),
                (
                    "default_port_consumption",
                    models.FloatField(
                        default=3.0,
                        help_text="MT/day in port if profile does not override",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Vessel Profile",
                "verbose_name_plural": "Vessel Parameters",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="VesselSpeedProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. CP, ECO, SUPER ECO", max_length=60
                    ),
                ),
                ("ballast_speed", models.FloatField(help_text="Knots")),
                ("laden_speed", models.FloatField(help_text="Knots")),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "vessel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="speed_profiles",
                        to="voyage.vesselprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vessel Speed Profile",
                "verbose_name_plural": "Vessel Speed Profiles",
                "ordering": ["vessel__name", "name"],
                "unique_together": {("vessel", "name")},
            },
        ),
        migrations.CreateModel(
            name="VesselFuelProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="e.g. CP CONS, ECO CONS", max_length=60),
                ),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "vessel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fuel_profiles",
                        to="voyage.vesselprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vessel Fuel Profile",
                "verbose_name_plural": "Vessel Fuel Profiles",
                "ordering": ["vessel__name", "name"],
                "unique_together": {("vessel", "name")},
            },
        ),
        migrations.CreateModel(
            name="FreightVoyage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=160, unique=True)),
                ("commodity", models.CharField(blank=True, max_length=80)),
                (
                    "load_ports",
                    models.JSONField(
                        default=list, help_text="One or many load port names"
                    ),
                ),
                (
                    "discharge_ports",
                    models.JSONField(
                        default=list, help_text="One or many discharge port names"
                    ),
                ),
                ("ballast_port", models.CharField(max_length=120)),
                ("load_rate", models.FloatField(help_text="MT/day")),
                ("discharge_rate", models.FloatField(help_text="MT/day")),
                ("turntime_load_hours", models.FloatField(default=12)),
                ("turntime_discharge_hours", models.FloatField(default=12)),
                ("port_exp_load_port", models.FloatField(default=0)),
                ("port_exp_discharge_port", models.FloatField(default=0)),
                ("misc_expenses", models.FloatField(default=0)),
                (
                    "intake_mode",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("calculated", "Calculated from vessel, draft and stowage"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                (
                    "intake_manual",
                    models.FloatField(default=0, help_text="MT if manual mode"),
                ),
                (
                    "draft_limit",
                    models.FloatField(
                        default=0, help_text="Optional limiting draft in meters"
                    ),
                ),
                (
                    "stowage_factor",
                    models.FloatField(
                        default=0, help_text="cbm/mt used for intake calc mode"
                    ),
                ),
                ("apply_same_sea_margin", models.BooleanField(default=True)),
                ("sea_margin_ballast_pct", models.FloatField(default=7)),
                ("sea_margin_laden_pct", models.FloatField(default=7)),
                (
                    "ballast_distance",
                    models.FloatField(help_text="NM total ballast leg"),
                ),
                ("laden_distance", models.FloatField(help_text="NM total laden leg")),
                ("address_commission_pct", models.FloatField(default=0)),
                ("brokerage_commission_pct", models.FloatField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "daily_hire_index",
                    models.ForeignKey(
                        blank=True,
                        help_text="Index whose daily value is target TCE for this voyage",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="hire_voyages",
                        to="voyage.availableindex",
                    ),
                ),
                (
                    "fuel_profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="voyages",
                        to="voyage.vesselfuelprofile",
                    ),
                ),
                (
                    "speed_profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="voyages",
                        to="voyage.vesselspeedprofile",
                    ),
                ),
                (
                    "vessel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="voyages",
                        to="voyage.vesselprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Freight Voyage",
                "verbose_name_plural": "Voyage Parameters",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="VoyageFuelSplit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weight_pct",
                    models.FloatField(
                        default=100, help_text="Weight in percentage points"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "fuel_index",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fuel_split_lines",
                        to="voyage.availableindex",
                    ),
                ),
                (
                    "voyage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fuel_splits",
                        to="voyage.freightvoyage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Voyage Fuel Split",
                "verbose_name_plural": "Voyage Fuel Splits",
                "ordering": ["voyage__name", "fuel_index__name"],
                "unique_together": {("voyage", "fuel_index")},
            },
        ),
        migrations.CreateModel(
            name="VesselFuelConsumption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fuel_type",
                    models.CharField(help_text="e.g. VLSFO, LSFO, MGO", max_length=60),
                ),
                (
                    "sea_consumption",
                    models.FloatField(default=0, help_text="MT/day at sea"),
                ),
                (
                    "port_consumption",
                    models.FloatField(default=0, help_text="MT/day in port"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "fuel_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fuel_lines",
                        to="voyage.vesselfuelprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vessel Fuel Consumption Line",
                "verbose_name_plural": "Vessel Fuel Consumption Lines",
                "ordering": [
                    "fuel_profile__vessel__name",
                    "fuel_profile__name",
                    "fuel_type",
                ],
                "unique_together": {("fuel_profile", "fuel_type")},
            },
        ),
    ]
