# Generated by Django 4.2 on 2026-06-08 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voyage', '0011_indexcodemapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='FFACurve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vessel_class', models.CharField(max_length=50)),
                ('raw_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='comparisonvessel',
            name='is_standard',
            field=models.BooleanField(default=False, help_text='BKI reference vessel'),
        ),
        migrations.CreateModel(
            name='FFACurvePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=20)),
                ('period_type', models.CharField(choices=[('balmo', 'Balance of Month'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('combined', 'Combined'), ('calendar_year', 'Calendar Year')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('bid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('offer', models.DecimalField(decimal_places=2, max_digits=10)),
                ('curve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='voyage.ffacurve')),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
    ]
