"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.

For more informatfffion on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settiffngs and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from decouple import config, Csv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-&am)wz9ys0g-^f5j47_ke4ahl)2pgys&g1plo0swlj#qhbp55@')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

# ALLOWED_HOSTS configuration for different environments
_allowed_hosts_env = config('ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=Csv())
ALLOWED_HOSTS = list(_allowed_hosts_env) if _allowed_hosts_env else []

# Always include localhost for development
ALLOWED_HOSTS.extend(['localhost', '127.0.0.1'])

# Add Render production domains
ALLOWED_HOSTS.extend([
    'freightdash.onrender.com',
    'freightdash-web.onrender.com',
])

# Remove duplicates while preserving order
seen = set()
ALLOWED_HOSTS = [x for x in ALLOWED_HOSTS if not (x in seen or seen.add(x))]


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'core',
    'voyage',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.menu_items',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

database_url = config('DATABASE_URL', default='').strip()
environment = config('ENVIRONMENT', default='development')
database_engine = config('DATABASE_ENGINE', default='')

# Use SQLite for local development if DATABASE_ENGINE is set to sqlite3
if database_engine == 'django.db.backends.sqlite3':
    DATABASES = {
        'default': {
            'ENGINE': database_engine,
            'NAME': config('DATABASE_NAME', default=BASE_DIR / 'db.sqlite3'),
        }
    }
elif database_url:
    import dj_database_url

    DATABASES = {
        'default': dj_database_url.parse(database_url, conn_max_age=600, conn_health_checks=True)
    }
    # Avoid server-side cursors in production; they can be invalidated when
    # transactions close before queryset iteration fully completes.
    DATABASES['default']['DISABLE_SERVER_SIDE_CURSORS'] = True
else:
    database_host = config('DATABASE_HOST', default='db')

    # Render can expose discrete Postgres variables depending on setup.
    render_db_name = config('PGDATABASE', default='').strip()
    render_db_user = config('PGUSER', default='').strip()
    render_db_password = config('PGPASSWORD', default='').strip()
    render_db_host = config('PGHOST', default='').strip()
    render_db_port = config('PGPORT', default='').strip()

    if all([render_db_name, render_db_user, render_db_password, render_db_host, render_db_port]):
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.postgresql',
                'NAME': render_db_name,
                'USER': render_db_user,
                'PASSWORD': render_db_password,
                'HOST': render_db_host,
                'PORT': int(render_db_port),
                'CONN_MAX_AGE': 600,
                'CONN_HEALTH_CHECKS': True,
                'ATOMIC_REQUESTS': True,
                'DISABLE_SERVER_SIDE_CURSORS': True,
            }
        }
    else:
        if environment == 'production' and database_host == 'db':
            raise RuntimeError(
                'Production database is misconfigured: DATABASE_URL is missing and DATABASE_HOST is still set to the local docker host "db".'
            )

        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.postgresql',
                'NAME': config('DATABASE_NAME', default='freightdash'),
                'USER': config('DATABASE_USER', default='postgres'),
                'PASSWORD': config('DATABASE_PASSWORD', default='changeme'),
                'HOST': database_host,
                'PORT': config('DATABASE_PORT', default='5432', cast=int),
                'CONN_MAX_AGE': 600,
                'CONN_HEALTH_CHECKS': True,
                'ATOMIC_REQUESTS': True,
                'DISABLE_SERVER_SIDE_CURSORS': True,
            }
        }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Singapore'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
# CompressedStaticFilesStorage serves gzip-compressed files without requiring
# a pre-built manifest JSON, avoiding startup failures on ephemeral containers.
STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# CSRF Settings
CSRF_TRUSTED_ORIGINS = config('CSRF_TRUSTED_ORIGINS', default='http://localhost:3000,http://localhost:8000', cast=Csv())

# Jazzmin (AdminLTE) Configuration - Optimized for performance
JAZZMIN_SETTINGS = {
    "site_title": "FreightDash Admin",
    "site_header": "FreightDash Administration",
    "site_brand": "FreightDash",
    "welcome_sign": "Welcome to FreightDash Admin",
    "copyright": "FreightDash © 2026",
    
    # Layout
    "show_sidebar": True,
    "navigation_expanded": False,
    "show_ui_builder": False,
    "language_chooser": False,
    "search_model": "auth.User",
    "custom_links": {
        "voyage": [
            {
                "name": "Upload Baltic Indices",
                "url": "admin:indices-upload",
                "icon": "fas fa-file-upload",
            },
            {
                "name": "Indices Display Config",
                "url": "admin:indices-config",
                "icon": "fas fa-sliders-h",
            },
        ]
    },
}

# Jazzmin UI Tweaks
JAZZMIN_UI_TWEAKS = {
    "navbar_small": False,
    "footer_small": False,
    "body_small": False,
    "brand_small": False,
    "brand_colour": "navbar-primary",
    "accent": "accent-primary",
    "navbar": "navbar-primary navbar-dark",
    "sidebar": "sidebar-dark-primary",
}

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
