"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.

For more informatfffion on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settiffngs and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from decouple import config, Csv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-&am)wz9ys0g-^f5j47_ke4ahl)2pgys&g1plo0swlj#qhbp55@')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

# ALLOWED_HOSTS configuration for different environments
_allowed_hosts_env = config('ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=Csv())
ALLOWED_HOSTS = list(_allowed_hosts_env) if _allowed_hosts_env else []

# Always include localhost for development
ALLOWED_HOSTS.extend(['localhost', '127.0.0.1'])

# Add Render production domains
ALLOWED_HOSTS.extend([
    'freightdash.onrender.com',
    'freightdash-web.onrender.com',
])

# Remove duplicates while preserving order
seen = set()
ALLOWED_HOSTS = [x for x in ALLOWED_HOSTS if not (x in seen or seen.add(x))]


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'nested_admin',
    'core',
    'voyage',
    'supply',
    'ob_forecast',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'core.middleware.LoginRequiredMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.menu_items',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

database_url = config('DATABASE_URL', default='').strip()
environment = config('ENVIRONMENT', default='development')
database_engine = config('DATABASE_ENGINE', default='')

if environment == 'production':
    if SECRET_KEY.startswith('django-insecure-'):
        raise RuntimeError(
            'Production deployment is using the insecure default SECRET_KEY. '
            'Set a strong SECRET_KEY environment variable.'
        )
    if DEBUG:
        raise RuntimeError('DEBUG must be False in production.')

# Use SQLite for local development if DATABASE_ENGINE is set to sqlite3
if database_engine == 'django.db.backends.sqlite3':
    DATABASES = {
        'default': {
            'ENGINE': database_engine,
            'NAME': config('DATABASE_NAME', default=BASE_DIR / 'db.sqlite3'),
        }
    }
elif database_url:
    import dj_database_url

    DATABASES = {
        'default': dj_database_url.parse(database_url, conn_max_age=600, conn_health_checks=True)
    }
else:
    database_host = config('DATABASE_HOST', default='db')

    # Render can expose discrete Postgres variables depending on setup.
    render_db_name = config('PGDATABASE', default='').strip()
    render_db_user = config('PGUSER', default='').strip()
    render_db_password = config('PGPASSWORD', default='').strip()
    render_db_host = config('PGHOST', default='').strip()
    render_db_port = config('PGPORT', default='').strip()

    if all([render_db_name, render_db_user, render_db_password, render_db_host, render_db_port]):
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.postgresql',
                'NAME': render_db_name,
                'USER': render_db_user,
                'PASSWORD': render_db_password,
                'HOST': render_db_host,
                'PORT': int(render_db_port),
                'CONN_MAX_AGE': 600,
                'CONN_HEALTH_CHECKS': True,
                'ATOMIC_REQUESTS': True,
            }
        }
    else:
        if environment == 'production' and database_host == 'db':
            raise RuntimeError(
                'Production database is misconfigured: DATABASE_URL is missing and DATABASE_HOST is still set to the local docker host "db".'
            )

        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.postgresql',
                'NAME': config('DATABASE_NAME', default='freightdash'),
                'USER': config('DATABASE_USER', default='postgres'),
                'PASSWORD': config('DATABASE_PASSWORD', default='changeme'),
                'HOST': database_host,
                'PORT': config('DATABASE_PORT', default='5432', cast=int),
                'CONN_MAX_AGE': 600,
                'CONN_HEALTH_CHECKS': True,
                'ATOMIC_REQUESTS': True,
            }
        }


# Postgres must avoid server-side cursors: they can be invalidated when a
# transaction closes before queryset iteration completes. Apply uniformly to
# any Postgres connection regardless of which config branch built it above.
if DATABASES['default'].get('ENGINE') == 'django.db.backends.postgresql':
    DATABASES['default']['DISABLE_SERVER_SIDE_CURSORS'] = True


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Singapore'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
# Project-level static sources (design-system CSS lives here).
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
# CompressedStaticFilesStorage serves gzip-compressed files without requiring
# a pre-built manifest JSON, avoiding startup failures on ephemeral containers.
STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# CSRF Settings
CSRF_TRUSTED_ORIGINS = config('CSRF_TRUSTED_ORIGINS', default='http://localhost:3000,http://localhost:8000', cast=Csv())

# Jazzmin (AdminLTE) Configuration
JAZZMIN_SETTINGS = {
    "site_title": "FreightDash Admin",
    "site_header": "FreightDash",
    "site_brand": "FreightDash",
    "welcome_sign": "Welcome to FreightDash",
    "copyright": "FreightDash © 2026",

    "show_sidebar": True,
    "navigation_expanded": True,
    "show_ui_builder": False,
    "language_chooser": False,
    "search_model": "auth.User",

    "icons": {
        "auth":                      "fas fa-shield-alt",
        "auth.user":                 "fas fa-user",
        "auth.group":                "fas fa-users",
        "core":                      "fas fa-cog",
        "core.menuitem":             "fas fa-bars",
        "voyage.dailyindexvalue":    "fas fa-chart-line",
        "voyage.availableindex":     "fas fa-list-ol",
        "voyage.customindexpreset":  "fas fa-bookmark",
        "voyage.routeparameters":    "fas fa-route",
        "voyage.vesselprofile":      "fas fa-ship",
        "voyage.vesselfuelprofile":  "fas fa-gas-pump",
        "voyage.freightvoyage":      "fas fa-anchor",
        "voyage.ffacurve":           "fas fa-chart-area",
        "supply.port":               "fas fa-anchor",
        "supply.trackedvessel":      "fas fa-ship",
        "supply.vesselstate":        "fas fa-location-dot",
        "supply.portcallevent":      "fas fa-exchange-alt",
        "supply.dailysupplysnapshot": "fas fa-layer-group",
        "supply.supplysignal":       "fas fa-satellite-dish",
        "ob_forecast":               "fas fa-water",
        "ob_forecast.obtonnagesnapshot": "fas fa-layer-group",
        "ob_forecast.obforecastsignal":  "fas fa-arrow-trend-up",
        "ob_forecast.obuploadlog":       "fas fa-file-import",
    },

    "order_with_respect_to": [
        # Freight Data (voyage): market data first, then vessel/freight config.
        "voyage.dailyindexvalue",
        "voyage.availableindex",
        "voyage.customindexpreset",
        "voyage.ffacurve",
        "voyage.routeparameters",
        "voyage.vesselprofile",
        "voyage.vesselfuelprofile",
        "voyage.freightvoyage",
        # Vessel Supply (supply).
        "supply.port",
        "supply.trackedvessel",
        "supply.vesselstate",
        "supply.portcallevent",
        "supply.dailysupplysnapshot",
        "supply.supplysignal",
        # OB Forecast (ob_forecast) — previously unordered, fell to the bottom.
        "ob_forecast.obtonnagesnapshot",
        "ob_forecast.obforecastsignal",
        "ob_forecast.obuploadlog",
        # System (core) + auth last.
        "core.menuitem",
        "auth.user",
        "auth.group",
    ],

    "custom_links": {
        "voyage": [
            {
                "name": "Upload: Daily EOD (Excel)",
                "url": "admin:upload-excel-indices",
                "icon": "fas fa-file-excel",
            },
            {
                "name": "Upload: Batch History (Excel)",
                "url": "admin:upload-batch-indices",
                "icon": "fas fa-table",
            },
            {
                "name": "Upload: PDF Report",
                "url": "voyage:upload_pdf_indices",
                "icon": "fas fa-file-pdf",
            },
            {
                "name": "Indices Display Config",
                "url": "admin:indices-config",
                "icon": "fas fa-sliders-h",
            },
        ],
        "core": [
            {
                "name": "Menu Builder",
                "url": "admin:menu-builder",
                "icon": "fas fa-pencil-ruler",
            },
            {
                "name": "Database Backup & Restore",
                "url": "admin:database-tools",
                "icon": "fas fa-database",
            },
            {
                "name": "Software Updates",
                "url": "admin:software-updates",
                "icon": "fas fa-cloud-arrow-down",
            },
        ],
    },
}

# Jazzmin UI Tweaks
JAZZMIN_UI_TWEAKS = {
    "navbar_small": False,
    "footer_small": False,
    "body_small": False,
    "brand_small": False,
    "brand_colour": "navbar-primary",
    "accent": "accent-primary",
    "navbar": "navbar-primary navbar-dark",
    "sidebar": "sidebar-dark-primary",
}

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Authentication
LOGIN_URL = '/admin/login/'
LOGOUT_REDIRECT_URL = '/admin/login/'

# AIS supply forecast: free aisstream.io websocket API key (one connection/key).
AISSTREAM_API_KEY = config('AISSTREAM_API_KEY', default='')

# Software version / update check (Software Updates admin page).
# APP_GIT_SHA / APP_BUILD_TIME are baked into the Docker image by CI; empty in
# local dev and in any image built before this feature.
APP_GIT_SHA = config('APP_GIT_SHA', default='')
APP_BUILD_TIME = config('APP_BUILD_TIME', default='')
# Repo whose default branch is compared against the running build.
GITHUB_REPO = config('GITHUB_REPO', default='juanvv-alt/FreightDash')
# Optional read-only token (only needed if the repo is private / for rate limits).
GITHUB_TOKEN = config('GITHUB_TOKEN', default='')
