# Generated by Django 4.2 on 2026-06-17 06:57

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OBUploadLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("zone", models.CharField(max_length=20)),
                ("series", models.CharField(max_length=20)),
                ("filename", models.CharField(max_length=255)),
                ("rows_added", models.IntegerField(default=0)),
                ("rows_skipped", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="OBTonnageSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                (
                    "zone",
                    models.CharField(
                        choices=[
                            ("NE_ASIA", "NE Asia"),
                            ("SE_ASIA", "SE Asia"),
                            ("AUSTRALIA", "Australia"),
                            ("EAST_PACIFIC", "East Pacific"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "series",
                    models.CharField(
                        choices=[
                            ("BALLAST_AT_SEA", "Ballast at Sea"),
                            ("IN_PORT", "In Port"),
                            ("TOTAL", "Total"),
                        ],
                        max_length=20,
                    ),
                ),
                ("vessel_count", models.IntegerField()),
                ("vessel_dwt", models.BigIntegerField(default=0)),
            ],
            options={
                "ordering": ["-date", "zone", "series"],
                "unique_together": {("date", "zone", "series")},
            },
        ),
        migrations.CreateModel(
            name="OBForecastSignal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                (
                    "zone",
                    models.CharField(
                        choices=[
                            ("NE_ASIA", "NE Asia"),
                            ("SE_ASIA", "SE Asia"),
                            ("AUSTRALIA", "Australia"),
                            ("EAST_PACIFIC", "East Pacific"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("bullish", "Bullish"),
                            ("bearish", "Bearish"),
                            ("neutral", "Neutral"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "score",
                    models.FloatField(help_text="Signed magnitude, roughly -3..+3"),
                ),
                ("confidence", models.FloatField(help_text="0..1")),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("regression", "Regression"),
                            ("zscore", "Z-score heuristic"),
                            ("snapshot", "Snapshot ratio (cold start)"),
                            ("insufficient", "Insufficient data"),
                        ],
                        max_length=20,
                    ),
                ),
                ("drivers", models.JSONField(blank=True, default=list)),
                ("data_days", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["-date", "zone"],
                "unique_together": {("date", "zone")},
            },
        ),
    ]
