# Generated by Django 4.2 on 2026-06-17 07:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ob_forecast", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="obtonnagesnapshot",
            name="vessel_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="obuploadlog",
            name="rows_added",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="obuploadlog",
            name="rows_skipped",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="obuploadlog",
            name="series",
            field=models.CharField(
                choices=[
                    ("BALLAST_AT_SEA", "Ballast at Sea"),
                    ("IN_PORT", "In Port"),
                    ("TOTAL", "Total"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="obuploadlog",
            name="zone",
            field=models.CharField(
                choices=[
                    ("NE_ASIA", "NE Asia"),
                    ("SE_ASIA", "SE Asia"),
                    ("AUSTRALIA", "Australia"),
                    ("EAST_PACIFIC", "East Pacific"),
                ],
                max_length=20,
            ),
        ),
    ]
